const $=id=>document.getElementById(id);let current=null,busy=false;
async function api(path,data){const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const value=await r.json();if(r.status===401)clearPrivate();if(!r.ok)throw Error(value.error||'Serveur indisponible.');return value;}
function clearPrivate(){current=null;$('workspace').hidden=true;$('login').hidden=false;for(const id of ['orders','archiveView','stepsRows','archiveSelect'])$(id).replaceChildren();$('search').value='';}
async function task(fn){if(busy)return;busy=true;$('message').textContent='';$('workspace').inert=true;try{await fn();}catch(e){$('message').textContent=e.message;}finally{busy=false;$('workspace').inert=false;}}
function table(snapshot,filter=''){const wrap=document.createElement('div');wrap.className='table';const t=document.createElement('table'),head=document.createElement('tr');for(const label of ['Lot / référence','Acheteur','Coordonnées','Plafond','Résultat','Validation']){const th=document.createElement('th');th.textContent=label;head.append(th);}t.append(head);
for(const o of snapshot.orders){if(filter&&!JSON.stringify(o).toLowerCase().includes(filter.toLowerCase()))continue;const lot=snapshot.lots.find(l=>l.number===o.lot);let result='En attente';
if(lot?.status==='sold')result=lot.leader===o.id?'Remporté — '+lot.price+' €':'Non remporté';
else if(lot?.status==='passed')result='Lot passé';else if(snapshot.sale.closed)result='Sans adjudication enregistrée';
const tr=document.createElement('tr');for(const value of [o.lot+' / '+o.id.slice(0,8),o.last_name+' '+o.name,o.phone+'\n'+o.email+'\n'+o.address,o.maximum+' €',result,o.approved_at?new Date(o.approved_at).toLocaleString('fr-FR'):'Ordre ancien']){const td=document.createElement('td');td.textContent=value;tr.append(td);}t.append(tr);}wrap.append(t);if(!snapshot.orders.length)wrap.textContent='Aucun ordre.';return wrap;}
function renderOrders(){$('orders').replaceChildren(table(current,$('search').value));}
function renderSteps(rows){$('stepsRows').replaceChildren();rows.forEach((row,i)=>{const section=document.createElement('div');section.className='card';section.dataset.range='true';for(const [key,label,value] of [['below','Prix inférieur à (€) — vide pour la dernière tranche',row.below??''],['buttons','Boutons proposés (séparés par des virgules)',row.buttons.join(', ')],['auto','Pas automatique (€)',row.auto]]){const id='range-'+i+'-'+key,l=document.createElement('label'),input=document.createElement('input');l.htmlFor=id;l.textContent=label;input.id=id;input.dataset.key=key;input.value=value;input.type=key==='buttons'?'text':'number';if(key!=='buttons')input.min='1';section.append(l,input);}const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent='Retirer la tranche';b.onclick=()=>section.remove();section.append(b);$('stepsRows').append(section);});}
function readSteps(){return [...$('stepsRows').children].map(el=>{const val=key=>el.querySelector('[data-key="'+key+'"]').value.trim();return {below:val('below')?Number(val('below')):null,buttons:val('buttons').split(',').map(n=>Number(n.trim())),auto:Number(val('auto'))};});}
async function load(){current=await api('/api/admin/current');$('login').hidden=true;$('workspace').hidden=false;$('saleTitle').textContent=current.sale.title;$('saleStatus').textContent=current.sale.closed?'Vente clôturée et archivée':'Vente ouverte';$('closeSale').disabled=current.sale.closed;$('newButton').disabled=!current.sale.closed;renderOrders();renderSteps(current.steps);const archives=await api('/api/admin/archives');$('archiveView').replaceChildren();$('archiveSelect').replaceChildren();const empty=document.createElement('option');empty.value='';empty.textContent='Choisir une archive';$('archiveSelect').append(empty);for(const a of archives){const o=document.createElement('option');o.value=a.id;o.textContent=a.title+' — '+new Date(a.closed).toLocaleString('fr-FR');$('archiveSelect').append(o);}}
$('login').onsubmit=e=>{e.preventDefault();task(async()=>{try{await api('/api/admin/login',{admin_code:$('pin').value});await load();}finally{$('pin').value='';}});};
$('refresh').onclick=()=>task(load);$('search').oninput=renderOrders;
$('logout').onclick=()=>task(async()=>{try{await api('/api/admin/logout',{});}finally{clearPrivate();}});
$('closeSale').onclick=()=>{if(confirm('Clôturer cette vente ? Les nouveaux ordres et les enchères seront bloqués. Les données seront conservées dans une archive.'))task(async()=>{await api('/api/admin/close',{sale_id:current.sale.id});await load();});};
$('newSale').onsubmit=e=>{e.preventDefault();task(async()=>{await api('/api/admin/new',{sale_id:current.sale.id,title:$('newTitle').value});$('newTitle').value='';$('archiveView').replaceChildren();await load();});};
$('archiveSelect').onchange=()=>task(async()=>{if(!$('archiveSelect').value){$('archiveView').replaceChildren();return;}const data=await api('/api/admin/archive/'+encodeURIComponent($('archiveSelect').value));const list=document.createElement('div');
const lotsTitle=document.createElement('h3');lotsTitle.textContent='Résultats de tous les lots';list.append(lotsTitle);
for(const lot of data.lots){const p=document.createElement('p');p.textContent='Lot '+lot.number+' — '+lot.title+' : '+(lot.status==='sold'?'Adjugé à '+lot.price+' €':lot.status==='passed'?'Passé':'Sans adjudication enregistrée');list.append(p);}
list.append(table(data));const h=document.createElement('h3');h.textContent='Historique des actions';list.append(h);for(const event of data.events){const p=document.createElement('p');p.textContent=new Date(event.time).toLocaleString('fr-FR')+' · Lot '+event.lot+' · '+event.message;list.append(p);}$('archiveView').replaceChildren(list);});
$('addRange').onclick=()=>{const rows=readSteps();rows.splice(Math.max(0,rows.length-1),0,{below:100,buttons:[5,10,20],auto:10});renderSteps(rows);};
$('stepsForm').onsubmit=e=>{e.preventDefault();task(async()=>{await api('/api/admin/steps',{sale_id:current.sale.id,steps:readSteps()});await load();$('message').textContent='Pas enregistrés. La console secrétaire les récupère automatiquement.';});};
window.addEventListener('pageshow',e=>{if(e.persisted){clearPrivate();task(load);}});
let activity=Date.now();for(const e of ['pointerdown','keydown'])document.addEventListener(e,()=>activity=Date.now());
setInterval(()=>{if(current&&!busy&&Date.now()-activity>300000)$('logout').click();},1000);
task(load);
